# Generated by Django 3.0.3 on 2020-03-30 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfiles', '0002_auto_20200330_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='si es que el proyecto pertenece a una empresa, indicar a cual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyectos.Empresa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='miembros',
            field=models.ManyToManyField(through='proyectos.MiembroProyecto', to='perfiles.Persona'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miembroproyecto',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miembroproyecto_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miembroproyecto',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miembroproyecto_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miembroproyecto',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Persona'),
        ),
        migrations.AddField(
            model_name='miembroproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
