# Generated by Django 3.0.3 on 2020-03-30 23:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import trabajos.models.trabajo
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maquinas', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('unidad', models.CharField(blank=True, help_text='indica la unidad con la que debería medirse el material.ej. "g", "cm^2"', max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(verbose_name='inicio')),
                ('fecha_termino', models.DateTimeField(blank=True, help_text='puede especificarte cuando termine la tarea', null=True, verbose_name='término')),
                ('cantidad_material', models.CharField(blank=True, help_text='indica la cantidad de material en la unidad indicada por el tipo seleccionado', max_length=64, null=True, verbose_name='cantidad de material')),
                ('material_fablab', models.BooleanField(default=True, help_text='marcar si el material pertenece al laboratorio', verbose_name='material de FabLab')),
                ('foto', models.ImageField(blank=True, help_text='una imagen que muestra el trabajo realizado', null=True, upload_to=trabajos.models.trabajo.work_picture_path)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajo_creadas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(help_text='la máquina donde se realizó el trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='maquinas.Maquina', verbose_name='máquina')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='trabajos.TipoMaterial', verbose_name='material')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajo_modificadas', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(help_text='la persona que operó la máquina durante la realización de la tarea', on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='perfiles.Persona')),
                ('solicitado_por', models.ForeignKey(blank=True, help_text='seleccionar si es que este trabajo fue solicitado por una persona distinta a la que operó la máquina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_solicitados', to='perfiles.Persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='explica cuándo tiene que ser utilizado este contexto', null=True, verbose_name='descripción')),
                ('trabajos', models.ManyToManyField(related_name='contextos', to='trabajos.Trabajo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
