# Generated by Django 3.0.3 on 2020-03-30 23:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import maquinas.models.mantenimiento
import maquinas.models.maquina
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=255)),
                ('fabricante', models.CharField(max_length=255)),
                ('link_manual', models.URLField(blank=True, help_text='preferentemente una versión PDF del manual', null=True, verbose_name='link al manual')),
                ('nombre_soporte', models.CharField(blank=True, help_text='nombre de la persona o empresa a contactar', max_length=255, null=True, verbose_name='nombre del soporte')),
                ('email_soporte', models.EmailField(max_length=254, verbose_name='correo de soporte')),
                ('telefono_soporte', models.CharField(blank=True, help_text='use el código de país, como +569...', max_length=12, null=True, verbose_name='teléfono de soporte')),
                ('factor_dificultad', models.SmallIntegerField(default=1, help_text='entre más alto, la máquina es más difícil de usar', verbose_name='factor de dificultad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=maquinas.models.maquina.machine_picture_path)),
            ],
            options={
                'verbose_name': 'clase de máquina',
                'verbose_name_plural': 'clases de máquina',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(help_text='el momento en que se realizó la tarea')),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('serie', models.CharField(blank=True, help_text='identificador único de la máquina', max_length=255, null=True, verbose_name='número de serie')),
                ('fecha_instalacion', models.DateField(verbose_name='fecha de instalación')),
                ('fecha_retiro', models.DateField(blank=True, help_text='una máquina retirada no aparece en la lista de máquinasactivas', null=True, verbose_name='fecha de retiro')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'máquina',
            },
        ),
        migrations.CreateModel(
            name='TipoClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'clasificación',
                'verbose_name_plural': 'clasificaciones',
            },
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('imagen', models.ImageField(blank=True, help_text='imagen que ayude a describir la tarea a realizar', null=True, upload_to=maquinas.models.mantenimiento.task_picture_path)),
                ('prioridad', models.PositiveSmallIntegerField(help_text='números más bajos van primero')),
                ('frecuencia', models.PositiveSmallIntegerField(help_text='cantidad de periodos con la que debería realizarse la tarea')),
                ('periodo', models.CharField(choices=[('H', 'Horas'), ('D', 'Días'), ('S', 'Semanas'), ('M', 'Meses'), ('E', 'Semestres'), ('A', 'Años')], default='D', help_text='periodicidad con que debería realizarse la tarea', max_length=1)),
                ('clase_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_de_mantenimiento', to='maquinas.ClaseMaquina', verbose_name='clase de máquina')),
            ],
            options={
                'verbose_name': 'tarea de mantenimiento',
                'verbose_name_plural': 'tareas de mantenimiento',
            },
        ),
    ]
