# Generated by Django 3.0.3 on 2020-03-30 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maquinas', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareamantenimiento_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareamantenimiento_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquina',
            name='clase_maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='maquinas.ClaseMaquina'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquina_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquina',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquina_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='maquinas.Maquina', verbose_name='máquina'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='realizado_por',
            field=models.ForeignKey(help_text='la persona que realizó la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='perfiles.Persona'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='maquinas.TareaMantenimiento'),
        ),
        migrations.AddField(
            model_name='clasemaquina',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_de_maquina', to='maquinas.TipoClasificacion'),
        ),
        migrations.AddField(
            model_name='clasemaquina',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasemaquina_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clasemaquina',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasemaquina_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
