# Generated by Django 3.0.3 on 2020-03-30 23:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import perfiles.models.persona
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='la fecha en que se realizó. en caso de que haya durado más de una sesión, la fecha de la sesión final')),
            ],
            options={
                'verbose_name': 'capacitación',
                'verbose_name_plural': 'capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(help_text='el número en su documento de identificación nacional o pasaporte', max_length=12, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, help_text='número de contacto personal, ingrese el código de país como +56 en caso de Chile', max_length=12, null=True, verbose_name='teléfono')),
                ('foto', models.ImageField(blank=True, help_text='foto personal para identificación, debe mostrar el rostro con claridad', null=True, upload_to=perfiles.models.persona.profile_picture_path, verbose_name='foto')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='información estructurada adicional', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='TipoCampus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('region', models.CharField(blank=True, choices=[('AI', 'Aisén del General Carlos Ibañez del Campo'), ('AN', 'Antofagasta'), ('AP', 'Arica y Parinacota'), ('AR', 'La Araucanía'), ('AT', 'Atacama'), ('BI', 'Biobío'), ('CO', 'Coquimbo'), ('LI', "Libertador General Bernardo O'Higgins"), ('LL', 'Los Lagos'), ('LR', 'Los Ríos'), ('MA', 'Magallanes'), ('ML', 'Maule'), ('NB', 'Ñuble'), ('RM', 'Región Metropolitana de Santiago'), ('TA', 'Tarapacá'), ('VS', 'Valparaíso')], max_length=2, null=True, verbose_name='región')),
            ],
            options={
                'verbose_name': 'campus',
                'verbose_name_plural': 'campus',
            },
        ),
        migrations.CreateModel(
            name='TipoCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'género',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'unidad',
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perfiles.Persona')),
                ('cargo', models.CharField(blank=True, help_text='posición que tiene dentro de la empresa o a qué se dedica', max_length=255, null=True, verbose_name='cargo')),
            ],
            options={
                'verbose_name_plural': 'perfiles profesionales',
            },
        ),
        migrations.CreateModel(
            name='PerfilUSM',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perfiles.Persona')),
                ('rol', models.CharField(blank=True, help_text='en caso de estudiantes', max_length=12, null=True, verbose_name='rol USM')),
                ('ingreso', models.PositiveSmallIntegerField(blank=True, help_text='año en que comienza su actividad principal', null=True, verbose_name='año de ingreso')),
                ('avance', models.PositiveSmallIntegerField(blank=True, help_text='en el caso de estudiantes, el año de su ramo más atrasado', null=True, verbose_name='año de avance')),
                ('prioridad', models.DecimalField(blank=True, decimal_places=3, help_text='en caso de estudiantes, el valor de su última prioridad', max_digits=8, null=True, verbose_name='prioridad académica')),
            ],
            options={
                'verbose_name': 'perfil USM',
                'verbose_name_plural': 'perfiles USM',
            },
        ),
    ]
