# Generated by Django 3.0.3 on 2020-03-30 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('maquinas', '0002_auto_20200330_2003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(blank=True, help_text='para motivos estadísticos, dejar en blanco si es que no desea especificar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='perfiles.TipoGenero'),
        ),
        migrations.AddField(
            model_name='persona',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='la cuenta de usuario con nombre, correo y contraseña', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='capacitador',
            field=models.ForeignKey(blank=True, help_text='la persona que realizó la capacitación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitador_de', to='perfiles.Persona'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='clase_maquina',
            field=models.ForeignKey(help_text='la clase de equipamiento sobre la que se capacitó', on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='maquinas.ClaseMaquina', verbose_name='clase de máquina'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='modificado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='persona',
            field=models.ForeignKey(help_text='el perfil de la persona capacitada', on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='perfiles.Persona'),
        ),
        migrations.AddField(
            model_name='perfilusm',
            name='actividad',
            field=models.ForeignKey(help_text='actividad principal que realiza en el campus', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_usm', to='perfiles.TipoActividad'),
        ),
        migrations.AddField(
            model_name='perfilusm',
            name='campus',
            field=models.ForeignKey(help_text='el campus al que está asociada la persona', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_usm', to='perfiles.TipoCampus'),
        ),
        migrations.AddField(
            model_name='perfilusm',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='en el caso de estar asociados a una carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usm', to='perfiles.TipoCarrera'),
        ),
        migrations.AddField(
            model_name='perfilusm',
            name='unidad',
            field=models.ForeignKey(help_text='la unidad a la que está vinculada', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_usm', to='perfiles.TipoUnidad'),
        ),
        migrations.AddField(
            model_name='perfilprofesional',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_profesionales', to='proyectos.Empresa'),
        ),
    ]
